name: link
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
    
  get: ^4.7.2
  
  # Networking
  dio: ^5.9.0    
  syncfusion_flutter_pdfviewer: ^31.1.20
  # UI Components
  google_fonts: ^6.1.0
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  url_launcher: ^6.3.2
  
  # Utils
  connectivity_plus: ^7.0.0
  share_plus: ^12.0.0
  path_provider: ^2.1.5
  equatable: ^2.0.7
  dio_cache_interceptor: ^4.0.3
  retry: ^3.1.2
  hive: ^2.2.3
  visibility_detector: ^0.4.0+2
  flutter_animate: ^4.5.0
  flutter_markdown_plus: ^1.0.5
  hive_flutter: ^1.1.0
  lottie: ^3.1.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.7
  hive_generator: ^2.0.1
  analyzer: ^6.4.1

flutter:
  uses-material-design: true
