name: link
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  # State Management
  get: ^4.7.2
  
  # Networking
  dio: ^5.9.0  
  # Deep Linking
  app_links: ^6.4.1
  
  # PDF with performance optimizations
  pdfx: ^2.6.0
  flutter_cache_manager: ^3.3.1
  
  # UI Components
  google_fonts: ^6.1.0
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  url_launcher: ^6.3.2
  
  # Utils
  logger: ^2.0.2
  get_storage: ^2.1.1
  connectivity_plus: ^6.1.5
  share_plus: ^11.1.0
  path_provider: ^2.1.2
  equatable: ^2.0.7
  dio_cache_interceptor: ^4.0.3
  retry: ^3.1.2
  hive: ^2.2.3
  visibility_detector: ^0.4.0+2
  flutter_animate: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
