final randomBookKeywords = [
  // Tech & learning
  'programming',
  'technology',
  'engineering',
  'science',
  'mathematics',
  'physics',
  'chemistry',
  'biology',
  'medicine',
  'psychology',
  'self-help',
  'education',
  'finance',
  'business',
  'economics',
  'law',

  // Arts & creativity
  'art',
  'music',
  'photography',
  'architecture',
  'design',
  'crafts',
  'cooking',
  'food',
  'gardening',
  'home decor',

  // Fiction genres
  'fantasy',
  'science fiction',
  'horror',
  'mystery',
  'thriller',
  'romance',
  'historical fiction',
  'literary fiction',
  'contemporary fiction',
  'young adult',
  'children',
  'poetry',
  'drama',
  'short stories',
  'graphic novels',
  'comics',
  'manga',
  'urban fantasy',
  'dystopian',
  'post-apocalyptic',
  'steampunk',
  'cyberpunk',
  'magical realism',
  'superhero',
  'adventure',
  'epic fantasy',
  'dark fantasy',
  'high fantasy',
  'low fantasy',

  // True stories / biography
  'biography',
  'memoirs',
  'autobiography',
  'history',
  'war',
  'true crime',
  'military',
  'survival',

  // Culture & society
  'travel',
  'spirituality',
  'religion',
  'philosophy',
  'mythology',
  'folklore',
  'legends',
  'sociology',
  'political science',
  'multicultural',

  // Lifestyle & hobbies
  'fitness',
  'health',
  'sports',
  'pets',
  'cars',
  'motorcycles',
  'aviation',
  'adventure',
  'quest',
  'coming-of-age',
  'chick lit',
  'lad lit',
  'romantic comedy',
  'paranormal romance',
  'historical romance',
  'erotica',
  'lgbtq+',
];